import { campaignCalendarLabel, defaultMaterialCosts, deriveCraftingStats, generateMonthlyEvents, materialRowsFromRecipe, materialStockToInventory } from "./forge-engine";
import type { CampaignState, ForgeItem, ForgeProject, InventoryItem, MaterialInventory, MaterialName } from "./forge-types";

const armor = (
  name: string,
  basePriceGp: number,
  materialRecipe: ForgeItem["materialRecipe"],
  options: Partial<ForgeItem> = {},
): ForgeItem => ({
  name,
  category: "armorsmithing",
  itemType: name.toLowerCase().includes("shield") || name.toLowerCase().includes("buckler") ? "shield" : "armor",
  complexity: "complex",
  basePriceGp,
  masterwork: true,
  qualityGoal: "dwarvencraft",
  materialRecipe,
  ...options,
});

const weapon = (
  name: string,
  basePriceGp: number,
  materialRecipe: ForgeItem["materialRecipe"],
  options: Partial<ForgeItem> = {},
): ForgeItem => ({
  name,
  category: "weaponsmithing",
  itemType: "weapon",
  complexity: "moderate",
  basePriceGp,
  masterwork: true,
  qualityGoal: "masterwork",
  materialRecipe,
  ...options,
});

const blacksmithing = (
  name: string,
  basePriceGp: number,
  materialRecipe: ForgeItem["materialRecipe"],
  options: Partial<ForgeItem> = {},
): ForgeItem => ({
  name,
  category: "blacksmithing",
  itemType: "other_metal",
  complexity: "complex",
  basePriceGp,
  masterwork: false,
  qualityGoal: "standard",
  materialRecipe,
  ...options,
});

const finesmithing = (
  name: string,
  basePriceGp: number,
  materialRecipe: ForgeItem["materialRecipe"],
  options: Partial<ForgeItem> = {},
): ForgeItem => ({
  name,
  category: "finesmithing",
  itemType: "tool",
  complexity: "simple",
  basePriceGp,
  masterwork: false,
  qualityGoal: "standard",
  materialRecipe,
  ...options,
});

const locksmithing = (
  name: string,
  basePriceGp: number,
  materialRecipe: ForgeItem["materialRecipe"],
  options: Partial<ForgeItem> = {},
): ForgeItem => ({
  name,
  category: "locksmithing",
  itemType: "tool",
  complexity: "moderate",
  basePriceGp,
  masterwork: false,
  qualityGoal: "standard",
  materialRecipe,
  ...options,
});

function recipeCost(materials: MaterialInventory, recipe: ForgeItem["materialRecipe"]): number {
  return (Object.entries(recipe) as Array<[MaterialName, number]>).reduce((total, [material, lbs]) => {
    if (lbs === undefined) return total;
    return total + lbs * (materials[material]?.gpPerLb ?? defaultMaterialCosts[material]);
  }, 0);
}

function project(
  materials: MaterialInventory,
  input: Pick<ForgeProject, "id" | "client" | "item" | "priority" | "trueContractValue" | "prestige" | "notes" | "resolutionMode"> &
    Partial<Pick<ForgeProject, "hoursInvested" | "requiredHours" | "craftDc" | "kind" | "economicMode" | "materialSupplyMode" | "payoutMode">>,
): ForgeProject {
  const stats = deriveCraftingStats(input.item, profile);
  const materialSupplyMode = input.materialSupplyMode ?? "taark_supplies";
  const materialCost = input.item.basePriceGp > 0 ? stats.rawMaterialCostGp : recipeCost(materials, input.item.materialRecipe);
  return {
    id: input.id,
    name: input.item.name,
    client: input.client,
    kind: input.kind ?? "paid_commission",
    economicMode: input.economicMode ?? "profit_bearing",
    materialSupplyMode,
    payoutMode: input.payoutMode ?? "true_contract_value",
    item: input.item,
    itemType: stats.itemType,
    status: "in_progress",
    priority: input.priority,
    trueContractValue: input.trueContractValue,
    listedItemValue: input.item.basePriceGp,
    materialCost,
    specialExpenses: 0,
    laborFee: Math.max(0, input.trueContractValue - materialCost),
    trueMargin: Math.max(0, input.trueContractValue - materialCost),
    requiredHours: input.requiredHours ?? stats.hours,
    hoursInvested: input.hoursInvested ?? 0,
    craftDc: input.craftDc ?? stats.dc,
    prestige: input.prestige,
    reputationEffectOnCompletion: input.prestige,
    materials: materialRowsFromRecipe(input.item.materialRecipe, materialSupplyMode === "client_supplies" ? "client" : "taark", materialSupplyMode === "client_reimburses"),
    notes: input.notes,
    resolutionMode: input.resolutionMode,
    take10: false,
  };
}

const inventoryItem = (id: string, item: ForgeItem, quantity: number, target: number): InventoryItem => ({
  id,
  item,
  quantity,
  target,
});

const seed = "brightaxe-starforge";
const profile: CampaignState["profile"] = {
  name: "Taark Brightaxe",
  title: "Master dwarven armorsmith beneath The Mermaid",
  reputation: 14,
  maxReputation: 20,
  skills: {
    armorsmithing: 37,
    weaponsmithing: 11,
    blacksmithing: 4,
    finesmithing: -1,
    locksmithing: 1,
  },
  craftRanks: {
    armorsmithing: 18,
    weaponsmithing: 10,
    blacksmithing: 5,
    finesmithing: 3,
    locksmithing: 5,
  },
  forgeQuality: "Masterwork",
  toolQuality: "Masterwork",
  forgeBonus: 2,
  toolBonus: 2,
  baseMonthlyHours: 300,
  ringOfSustenanceHours: 120,
  genericShopCostsGp: 100,
  shopProfitBaselineGp: 1700,
  commissionAnchorGp: 1400,
  commissionSpikeCapGp: 1000,
  dmTargetProfitGp: 2000,
  dmTargetVolatilityGp: 500,
  perfectionismWastePct: 45,
};
const materials = materialStockToInventory({
  Iron: 240,
  Steel: 420,
  Copper: 80,
  Tin: 24,
  Bronze: 90,
  Brass: 45,
  Lead: 60,
  "Cold Iron": 35,
  "Alchemical Silver": 28,
  Silver: 70,
  Electrum: 8,
  Gold: 35,
  Platinum: 4,
  Mithril: 25,
  Adamantine: 60,
});

const projects = [
  project(materials, {
    id: "basenhack-full-plate",
    client: "Basenhack Clan",
    item: armor("Basenhack Clan Full Plate", 2300, { Steel: 55, Silver: 4 }),
    priority: "high",
    trueContractValue: 3200,
    prestige: 2,
    notes: "Elite clan commission and Taark's current primary project.",
    resolutionMode: "fixedHours",
    requiredHours: 260,
    hoursInvested: 94,
    economicMode: "reputation_only",
    payoutMode: "no_payment",
    kind: "contest_prize",
  }),
  project(materials, {
    id: "fairstream-breastplate",
    client: "Captain Fairstream",
    item: armor("Adamantine Breastplate", 6200, { Adamantine: 35, Steel: 12 }, { specialMaterial: "Adamantine" }),
    priority: "medium",
    trueContractValue: 7600,
    prestige: 1,
    notes: "Consumes precious adamantine inventory.",
    resolutionMode: "craftingPdf",
    hoursInvested: 12,
    materialSupplyMode: "client_reimburses",
    economicMode: "reputation_only",
    payoutMode: "materials_only",
  }),
  project(materials, {
    id: "purple-worm-tooth",
    client: "Private Monster Hunter",
    item: weapon("Purple Worm Tooth Weapon", 1800, { Steel: 10, Silver: 2 }, { complexity: "very-complex" }),
    priority: "medium",
    trueContractValue: 2600,
    prestige: 2,
    notes: "Exotic prestige-oriented commission.",
    resolutionMode: "craftingPdf",
    hoursInvested: 0,
    economicMode: "reputation_only",
    payoutMode: "no_payment",
    kind: "prestige_commission",
  }),
  project(materials, {
    id: "iron-doors-mermaid",
    client: "The Mermaid",
    item: blacksmithing("Reinforced Iron Doors", 900, { Iron: 160, Steel: 20 }),
    priority: "medium",
    trueContractValue: 1400,
    prestige: 0,
    notes: "Heavy iron door commission for the tavern/forge entryways.",
    resolutionMode: "fixedHours",
    hoursInvested: 0,
    economicMode: "reputation_only",
    payoutMode: "no_payment",
  }),
];

export const initialCampaignState: CampaignState = {
  version: 2,
  currentMonth: 1,
  monthLabel: campaignCalendarLabel(1),
  profile,
  materials,
  inventory: [
    inventoryItem("scale-mail-mw", armor("Scale Mail (MW)", 200, { Steel: 35 }), 2, 3),
    inventoryItem("breastplate-mw", armor("Breastplate (MW)", 350, { Steel: 30 }), 2, 5),
    inventoryItem("chain-shirt-mw", armor("Chain Shirt (MW)", 250, { Steel: 25 }), 2, 5),
    inventoryItem("mithril-chain-shirt", armor("Mithril Chain Shirt", 1100, { Mithril: 12 }, { specialMaterial: "Mithril" }), 1, 2),
    inventoryItem("mithril-breastplate", armor("Mithril Breastplate", 4200, { Mithril: 18 }, { specialMaterial: "Mithril" }), 1, 2),
    inventoryItem("mithril-buckler", armor("Mithril Buckler", 1015, { Mithril: 5 }, { complexity: "moderate", specialMaterial: "Mithril" }), 0, 2),
    inventoryItem("mithril-light-shield", armor("Mithril Light Shield", 1009, { Mithril: 8 }, { complexity: "moderate", specialMaterial: "Mithril" }), 0, 2),
    inventoryItem("adamantine-breastplate", armor("Adamantine Breastplate", 6200, { Adamantine: 35, Steel: 12 }, { specialMaterial: "Adamantine" }), 0, 1),
    inventoryItem("adamantine-shield", armor("Adamantine Heavy Shield", 3020, { Adamantine: 18, Steel: 4 }, { complexity: "moderate", specialMaterial: "Adamantine" }), 0, 1),
    inventoryItem("adamantine-half-plate", armor("Adamantine Half-Plate", 10600, { Adamantine: 44, Steel: 12 }, { specialMaterial: "Adamantine" }), 0, 1),
    inventoryItem("tower-shield", armor("Tower Shield", 30, { Steel: 20 }, { complexity: "moderate", masterwork: false }), 2, 3),
    inventoryItem("heavy-steel-shield", armor("Heavy Steel Shield", 20, { Steel: 12 }, { complexity: "moderate", masterwork: false }), 3, 5),
    inventoryItem("light-steel-shield", armor("Light Steel Shield", 9, { Steel: 8 }, { complexity: "moderate", masterwork: false }), 3, 5),
    inventoryItem("buckler", armor("Buckler", 15, { Steel: 5 }, { complexity: "moderate", masterwork: false }), 4, 8),
    inventoryItem("full-plate-mw", armor("Full Plate (MW)", 1650, { Steel: 50 }), 0, 2),
    inventoryItem("half-plate-mw", armor("Half-Plate (MW)", 600, { Steel: 42 }), 0, 2),
    inventoryItem("chainmail-dc", armor("Chainmail", 150, { Steel: 40 }), 0, 3),
    inventoryItem("splint-mail-dc", armor("Splint Mail", 200, { Steel: 45 }), 0, 2),
    inventoryItem("banded-mail-dc", armor("Banded Mail", 250, { Steel: 45 }), 0, 2),
    inventoryItem("mithril-chainmail", armor("Mithril Chainmail", 5150, { Mithril: 28 }, { specialMaterial: "Mithril" }), 0, 1),
    inventoryItem("mithril-full-plate", armor("Mithril Full Plate", 10500, { Mithril: 35 }, { specialMaterial: "Mithril" }), 0, 1),
    inventoryItem("adamantine-chain-shirt", armor("Adamantine Chain Shirt", 5250, { Adamantine: 25, Steel: 6 }, { specialMaterial: "Adamantine" }), 0, 1),
    inventoryItem("adamantine-full-plate", armor("Adamantine Full Plate", 16500, { Adamantine: 55, Steel: 14 }, { specialMaterial: "Adamantine" }), 0, 1),
    inventoryItem("shield-spikes-dc", armor("Shield Spikes", 10, { Steel: 4 }, { complexity: "simple", itemType: "shield" }), 0, 4),
    inventoryItem("spiked-heavy-shield", armor("Spiked Heavy Shield", 30, { Steel: 14 }, { complexity: "moderate", itemType: "shield" }), 0, 2),
    inventoryItem("battleaxe-mw", weapon("Battleaxe (MW)", 310, { Steel: 8 }), 1, 2),
    inventoryItem("warhammer-mw", weapon("Warhammer (MW)", 312, { Steel: 8 }), 1, 2),
    inventoryItem("longsword-mw", weapon("Longsword (MW)", 315, { Steel: 6 }), 1, 2),
    inventoryItem("dagger-mw", weapon("Dagger (MW)", 302, { Steel: 2 }), 2, 4),
    inventoryItem("handaxe-mw", weapon("Handaxe (MW)", 306, { Steel: 5 }), 0, 2),
    inventoryItem("short-sword-mw", weapon("Short Sword (MW)", 310, { Steel: 5 }), 0, 2),
    inventoryItem("mace-mw", weapon("Heavy Mace (MW)", 312, { Steel: 7 }), 0, 2),
    inventoryItem("spearheads-mw", weapon("Spearheads (MW)", 120, { Steel: 6 }, { complexity: "simple" }), 0, 4),
    inventoryItem("greataxe-mw", weapon("Greataxe (MW)", 320, { Steel: 12 }), 0, 1),
    inventoryItem("dwarven-waraxe-mw", weapon("Dwarven Waraxe (MW)", 330, { Steel: 10 }), 0, 2),
    inventoryItem("greatsword-mw", weapon("Greatsword (MW)", 350, { Steel: 12 }), 0, 1),
    inventoryItem("morningstar-mw", weapon("Morningstar (MW)", 308, { Steel: 7 }), 0, 2),
    inventoryItem("scimitar-mw", weapon("Scimitar (MW)", 315, { Steel: 6 }), 0, 1),
    inventoryItem("rapier-mw", weapon("Rapier (MW)", 320, { Steel: 5 }), 0, 1),
    inventoryItem("arrowheads-mw", weapon("Arrowheads Batch (MW)", 60, { Steel: 3 }, { complexity: "simple" }), 0, 6),
    inventoryItem("lance-heads-mw", weapon("Lance Heads (MW)", 115, { Steel: 8 }, { complexity: "simple" }), 0, 2),
    inventoryItem("crossbow-parts-mw", weapon("Crossbow Metalwork (MW)", 335, { Steel: 8, Brass: 1 }), 0, 2),
    inventoryItem("simple-lock-mw", locksmithing("Simple Lock", 120, { Steel: 2, Brass: 1 }), 1, 4),
    inventoryItem("good-lock-mw", locksmithing("Good Lock", 220, { Steel: 3, Brass: 1 }), 0, 3),
    inventoryItem("reinforced-lockset-mw", locksmithing("Reinforced Lockset", 360, { Steel: 6, Brass: 2 }), 0, 2),
    inventoryItem("average-lock", locksmithing("Average Lock", 80, { Steel: 2, Brass: 1 }), 0, 4),
    inventoryItem("superior-lock", locksmithing("Superior Lock", 150, { Steel: 4, Brass: 2 }), 0, 1),
    inventoryItem("padlocks", locksmithing("Padlocks", 60, { Steel: 2, Brass: 1 }, { complexity: "simple" }), 0, 6),
    inventoryItem("key-blanks", locksmithing("Key Blanks", 25, { Brass: 1 }, { complexity: "very-simple" }), 0, 12),
    inventoryItem("manacles", locksmithing("Manacles", 15, { Steel: 5 }), 0, 3),
    inventoryItem("strongbox-hardware", locksmithing("Strongbox Hardware", 95, { Steel: 5, Brass: 1 }), 0, 2),
    inventoryItem("hinges-mw", blacksmithing("Reinforced Hinges", 90, { Steel: 8 }, { complexity: "simple" }), 1, 4),
    inventoryItem("buckles-clasps-mw", finesmithing("Buckles and Clasps", 80, { Brass: 2, Steel: 1 }), 1, 5),
    inventoryItem("armor-fittings-mw", finesmithing("Armor Fittings", 140, { Brass: 3, Steel: 2 }), 1, 4),
    inventoryItem("lantern-frames-mw", finesmithing("Lantern Frames", 120, { Brass: 4, Copper: 1 }), 0, 3),
    inventoryItem("jewelry-fittings-mw", finesmithing("Jewelry Fittings", 180, { Silver: 1, Gold: 0.25 }), 0, 2),
    inventoryItem("nails-rivets", blacksmithing("Nails and Rivets", 20, { Steel: 4 }, { complexity: "very-simple" }), 0, 10),
    inventoryItem("horseshoes", blacksmithing("Horseshoes", 35, { Steel: 6 }, { complexity: "simple" }), 0, 8),
    inventoryItem("chain-lengths", blacksmithing("Chain Lengths", 50, { Steel: 10 }), 0, 4),
    inventoryItem("iron-bands", blacksmithing("Iron Bands", 30, { Iron: 12 }, { complexity: "simple" }), 0, 6),
    inventoryItem("cauldron-hooks", blacksmithing("Cauldron Hooks", 24, { Iron: 8 }, { complexity: "simple" }), 0, 3),
    inventoryItem("grates", blacksmithing("Hearth Grates", 75, { Iron: 25 }), 0, 2),
    inventoryItem("door-hardware", blacksmithing("Door Hardware", 65, { Iron: 14, Steel: 4 }), 0, 4),
  ],
  projects,
  events: generateMonthlyEvents(1, seed),
  labor: {
    projectHours: {
      "basenhack-full-plate": 160,
      "fairstream-breastplate": 110,
      "purple-worm-tooth": 80,
      "iron-doors-mermaid": 60,
    },
    genericInventory: 80,
    repairs: 40,
    apprenticeTraining: 40,
    miscellaneous: 15,
  },
  ledger: [],
  settings: {
    tableFacing: true,
    resolutionStyle: "dm-editable",
    craftingDefault: "craftingPdf",
    randomSeed: seed,
    materialBalancingMode: "profit_coupled",
    materialSupplyPolicy: "guild_auto_supplies",
  },
};
